name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        run: |
          test -f index.html

      - name: Slack Notification
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            MESSAGE="✅ CI Pipeline succeeded for devops-webapp"
          else
            MESSAGE="❌ CI Pipeline failed for devops-webapp"
          fi

          curl -X POST \
            -H "Content-Type: application/json" \
            --data "{\"text\":\"$MESSAGE\"}" \
            "${{ secrets.SLACK_WEBHOOK_URL }}"
